#!/bin/bash
#
# ver - скрипт для отображения базовой информации о релизе дистрибутива
#
# Copyright (C) Linuxoid85, LinuxSovet Commiunity, 2021.
#

source /etc/lsb-release

echo -e "Welcome to $DISTRIB_ID!

Version: $DISTRIB_RELEASE
Codename: $DISTRIB_CODENAME

Site: https://github.com/Linuxoid85/CalmiraLinux

"
