#!/bin/bash

#
# cpkgi - script for install packages in Calmira GNU/Linux
#
# Copyright (C) Linuxoid85, LinuxSovet Commiunity
# 2021
#

source /usr/user/cpkg-tools/resources.sh
test_directory

if [ `whoami` -ne "root" ]; then
	echo -e "\e[1;31mERROR! Please run this script on root. \e[0m"
	exit 0
fi

install_pkg() {
	# Function for install package
	if [ $1 = '' ]; then
		echo -e "\e[1;31mERROR! Select package. \e[0m"
		exit 0
	fi

	if test -f "$1.tar.xz"; then
		cp $1.tar.xz /var/cache/cpkgi/ && cd /var/cache/cpkgi

		read -p "List package (Y/n)? " run
		if [ $run = "Y" ]; then
			echo -e "\n\e[1mPackage $1:\e[0m"
			tar -listf $1.tar.xz
		else
			echo "No."
		fi
		echo

		read -p "Unpack package (Y/n)? " run
		if [ $run = "Y" ]; then
			tar -xf $1.tar.xz && cd $1
		else
			echo "No. Exit."
			exit 0
		fi

		read -p "Install package (Y/n)? " run
		if [ $run = "Y" ]; then
			source config
			echo -e "\n\e[1mDependences:\e[0m \n"
			echo "$DEP"
			
			echo -e "\n\nCreate package directory..."
			
			echo "Copy package data..."
			
			echo "Test usr dir..."
			if test -d usr; then
				cp -r usr /
				echo -e "Copy data into /usr/usr \e[1;32mdone.\e[0m"
			fi
			
			echo -n "Test package..."
			if test -f /usr/bin/$1; then
				echo -e "\e[1;32mDone\e[0m !"
				exit 0
			fi

			echo -n -e "Write pkg file information to cpkg-tools-DB..."
			echo "$FILES" > /usr/share/cpkg-tools/database.d/$PKGNAME
			if grep "$FILES" /usr/share/cpkg-tools/database.d/$PKGNAME; then
				echo -e "\e[1;32mDone.\e[0m"
			else
				echo -e "\e[1;31mERROR.\e[0m"
			fi

			#echo -e "\e[1;32mDone.\e[0m"
		else
			echo "No. Exit."
			exit 0
		fi
	else
		echo -e "e[1;101mError\e[0m ! Package $1.tar.xz not found! Exit."
		exit 0
	fi
}

install_pkg $1
