# Begin /etc/bashrc
# Written for Calmira LX4 1.1 Linux
# by Michail Krasnov <linuxoid85@gmail.com>

system_welcome

## Aliases
alias ls='ls -l'
alias cls='clear'
alias edit='vim'
alias help='man bash'
